// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "0a5688a3-c07b-4a27-a270-13766e009a77";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLatidosChange();
void onTemperaturaChange();
void onCaidaChange();

float latidos;
float temperatura;
bool caida;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(latidos, READWRITE, ON_CHANGE, onLatidosChange);
  ArduinoCloud.addProperty(temperatura, READWRITE, ON_CHANGE, onTemperaturaChange);
  ArduinoCloud.addProperty(caida, READWRITE, ON_CHANGE, onCaidaChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
